Feature/alerta abr1
MinisterioPublicoRJ/alertas pull request #30
Opened 2020-10-28 17:29 UTC by rhenanbartels

Implementa script do Alerta **ABR1**

2020-10-28 19:27 UTC, bernardoccordeiro commented on src/alertas/jobs.py
Tem que tirar o "test" dos nomes, e descomentar os outros alertas.

2020-10-28 19:31 UTC, bernardoccordeiro requested changes
Precisa descomentar os outros alertas e mudar o nome das tabelas pro nome padrão

2020-10-28 20:20 UTC, rhenanbartels commented on src/alertas/jobs.py
resolved in 563a1f2c4ddef82715

2020-10-29 18:02 UTC, bernardoccordeiro approved these changes

2020-10-29 18:02 UTC, merged