Feature/alerta fbet
MinisterioPublicoRJ/alertas pull request #38
Opened 2020-12-16 13:21 UTC by rhenanbartels

2020-12-16 19:43 UTC, bernardoccordeiro commented on src/alertas/alerta_febt.py
> +            datediff(current_timestamp(), MAX(proc_data)) diff_ultimo_envio
Ao que parece, a data em que o RO chegou ao MP é a data_liberacao, não? Ao invés de proc_data

2020-12-16 20:09 UTC, rhenanbartels commented on src/alertas/alerta_febt.py
> +            datediff(current_timestamp(), MAX(proc_data)) diff_ultimo_envio
@SamambaMan

2020-12-17 14:03 UTC, SamambaMan requested changes
corte cirúrgico

2020-12-17 14:18 UTC, SamambaMan approved these changes

2020-12-17 14:19 UTC, merged